### ISSUE TITLE
[improvement] iFrame Sandbox

### ISSUE THREAD

**Issue by rafaelfaustini** [Baruffi/no-forum#1]
In order to solve the problem of the menu being interfered by the custom HTML/CSS. I suggest to approach in a similar way as codepen does, by using iFrame to render new html and using sandbox property for security reasons.

**Comment by Baruffi** [comment]
Hello and thanks for the suggestion!

I have tried a few implementations using an iFrame to wrap the user inputted content (as opposed to the current div). Although effective in keeping the css separate from the main page, turns out it poses a few hurdles; mainly due to the user's hability to interact with the fragments by hovering over them. The main problems I encountered are the following:

1. As far as I can tell, communication between an iFrame and the main page isn't an intended feature in react, requiring a custom implementation handling the necessary reloads almost manually (best react can do on its own is fully reload the iframe if you edit a state connected to its root).
2. It poses the question of whether to use srcdoc or src with a separate link. While srcdoc is more direct and can be applied to the user content itself, src is definitely the only way to preserve current javascript behavior. Even then, while attempting to implement it that way using [contexts](https://pt-br.reactjs.org/docs/context.html), the real-time behavior was completely lost and some of the required modifications were questionable at best. It might be a possibility if a complete rework of the current implementation is made, having iFrames in mind, but so far I dont see it as being viable.
3. Even if handled directly in html, replicating the current tooltip behavior would require an exchange of javascript messages between the iFrame and the main page. While this seems to be a [supported feature](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), it would be completely bypassing the react framework. Therefore, I don't see it as a viable option either.

As an addendum, I also tried to make use of [portals](https://reactjs.org/docs/portals.html) but they gave me by far the least consistent results, so I quickly abandoned that idea.

If you have any suggestions on how to tackle these issues let me know!
